### ISSUE TITLE
When restarting the container image fails to re-bind to the same IP

### ISSUE THREAD

**Issue by StephenShamakian** [milanmdev/whisker-private-api#42]
If I assign a static IP to this container in Unraid it starts fine on that IP/Port. But if I go and restart or stop/start the container it returns this error:

`node:internal/errors:563
    ErrorCaptureStackTrace(err);
    ^

Error: listen EADDRINUSE: address already in use /tmp/tsx-0/34.pipe
    at Server.setupListenHandle [as _listen2] (node:net:1855:21)
    at listenInCluster (node:net:1920:12)
    at Server.listen (node:net:2025:5)
    at file:///build/node_modules/tsx/dist/cli.mjs:53:31317
    at new Promise (<anonymous>)
    at yn (file:///build/node_modules/tsx/dist/cli.mjs:53:31295)
    at async file:///build/node_modules/tsx/dist/cli.mjs:55:459 {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '/tmp/tsx-0/34.pipe',
  port: -1
}

Node.js v20.11.0
error Command failed with exit code 1.
yarn run v1.22.19
$ tsx ./src/index.ts
[LAUNCHED] Whisker Private API launched at http://localhost:8080
yarn run v1.22.19
$ tsx ./src/index.ts
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

It seems like the IP/Port is not being released properly when the container shuts down?

**Comment by StephenShamakian** [comment]
Also if I change the IP to another IP start/stop. Then change it back to its original IP it binds successfully (until container restart again).

**Comment by milanmdev** [comment]
The latest version of the api (1.0.3) should work. There was a bug in tsx that caused that to happen. The new version should be available on Docker now.
